version: "3"

services:
  exekube:
    image: ilyasotkov/exekube:0.1.0-rc.2
    working_dir: /project
    environment:
      TF_INPUT: "0"
      TF_LOG: ""
      XK_LIVE_DIR: /project/live
      GOOGLE_CREDENTIALS: /project/owner-key.json
      TF_VAR_gcp_project: continuous-integration-194808
      TF_VAR_gcp_remote_state_bucket: continuous-integration-194808-tfstate
    ports:
      - 8001:8001
    volumes:
      - .:/project
      - ./.cache/helm:/root/.helm
      - ./.cache/terragrunt:/root/.terragrunt
      - ./.cache/gcloud:/root/.config/gcloud
      - ./.cache/kube:/root/.kube
    command: kubectl proxy --address="0.0.0.0" --accept-hosts ".*"
