version: "2"

services:
  exekube:
    image: ilyasotkov/exekube:latest
    # image: exekube-ksonnet:latest
    working_dir: /project
    environment:
      TF_INPUT: "0"
      TF_LOG:
      USER: root
    env_file:
      - ./live/prod/secrets/.env
    ports:
      - 8001:8001
    volumes:
      # - ../exekube/modules:/exekube-modules
      # - ../exekube/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
      - .:/project
      - ./.cache/helm:/root/.helm
      - ./.cache/terragrunt:/root/.terragrunt
      - ./.cache/gcloud:/root/.config/gcloud
      - ./.cache/kube:/root/.kube
    command: kubectl proxy --address="0.0.0.0" --accept-hosts ".*"
