version: "2"

services:
  exekube:
    image: ilyasotkov/exekube:0.2-alpha.1
    working_dir: /project
    environment:
      TF_INPUT: "0"
      TF_LOG:
      USER: root
    env_file:
      - ./live/.env
      - ./live/prod/.env
    ports:
      - 8001:8001
    volumes:
      - ../exekube/modules:/exekube-modules
      - ../exekube/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
      - .:/project
      - ./.cache/helm:/root/.helm
      - ./.cache/terragrunt:/root/.terragrunt
      - ./.cache/gcloud:/root/.config/gcloud
      - ./.cache/kube:/root/.kube
    command: kubectl proxy --address="0.0.0.0" --accept-hosts ".*"
