version: "3"

services:
  exekube:
    image: ilyasotkov/exekube:0.1.0-rc.3
    working_dir: /project
    environment:
      TF_INPUT: "0"
      TF_LOG:
    env_file:
      - ./live/prod/.env
    ports:
      - 8001:8001
    volumes:
      - .:/project
      - ./.cache/helm:/root/.helm
      - ./.cache/terragrunt:/root/.terragrunt
      - ./.cache/gcloud:/root/.config/gcloud
      - ./.cache/kube:/root/.kube
    command: kubectl proxy --address="0.0.0.0" --accept-hosts ".*"
