controller:
  config:
    server-tokens: "false"
  service:
    loadBalancerIP: "35.205.239.8"
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 50

rbac:
  create: true
  serviceAccountName: default
